server:
  port: 8086

spring:
  application:
    name: iot-alarm-service

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/next_iot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: flink_user
    password: flink_pass
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1
      # 可替换点：当前使用 MySQL，后续应迁移 Redis / ES 用于高并发场景

  # Kafka 配置
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      # 消费告警事件的 topic
      topics: alarm-event-topic
      group-id: alarm-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest  #消费最新点位数据
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate
      type: batch # 开启批量消费
    properties:
      metric-topic: metric-topic # 自定义配置

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.nextiot.common.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# 日志配置
logging:
  level:
    com.nextiot: debug

# 自定义业务配置
iot:
  metric-topic: metric-topic